---
  - name: Setup workers
    hosts: all
    become: yes
    tasks:

    - name: Ensure kubelet is enabled (auto-start on boot)
      ansible.builtin.service:
        name: kubelet
        enabled: true

    - name: Ensure kubelet is started
      ansible.builtin.service:
        name: kubelet
        state: started

    # Step 18: Get join command from controller
    - name: Check if worker already joined the cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Fetch join command from controller
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_cmd
      when: not kubelet_conf.stat.exists

    # Step 19: Join worker to cluster
    - name: Join the Kubernetes cluster
      ansible.builtin.shell: "{{ join_cmd.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: not kubelet_conf.stat.exists #workers donâ€™t ask for join command after they have already joined
