{{- range $name, $version := .Values.app.versions }}
{{- if $version.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-checker-app-{{ $name }}
  labels:
    app: sms-checker-app
    version: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-checker-app
      version: {{ $name }}
  template:
    metadata:
      labels:
        app: sms-checker-app
        version: {{ $name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: sms-checker-app
          image: {{ $version.image }}
          imagePullPolicy: {{ $version.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ $version.port }}
          env:
            - name: MODEL_HOST
              value: "http://model-service-{{ $name }}:8081"
{{- end }}
{{- end }}
