{{- range $name, $version := .Values.app.versions }}
{{- if $version.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-checker-app-{{ $name }}
  labels:
    app: sms-checker-app
    version: {{ $name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-checker-app
      version: {{ $name }}
  template:
    metadata:
      labels:
        app: sms-checker-app
        version: {{ $name }}
    spec:
      containers:
        - name: sms-checker-app
          image: {{ $version.image }}
          ports:
            - containerPort: {{ $version.port }}
{{- end }}
{{- end }}
