apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-checker-app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-checker-app
      version: v1
  template:
    metadata:
      labels:
        app: sms-checker-app
        version: v1
    spec:
      containers:
        - name: sms-checker-app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_PORT
              value: "{{ .Values.app.port }}"
            - name: MODEL_HOST
              value: "http://model-service"   
            - name: APP_VERSION
              value: "{{ .Values.app.versions.v1.versionLabel }}" 

          envFrom:
            - configMapRef:
                name: sms-checker-config
            - secretRef:
                name: sms-checker-secret
          ports:
            - containerPort: {{ .Values.app.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-checker-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-checker-app
      version: v2
  template:
    metadata:
      labels:
        app: sms-checker-app
        version: v2
    spec:
      containers:
        - name: sms-checker-app
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: APP_PORT
              value: "{{ .Values.app.port }}"
            - name: MODEL_HOST
              value: "http://model-service"
            - name: APP_VERSION
              value: "{{ .Values.app.versions.v2.versionLabel }}" 
          envFrom:
            - configMapRef:
                name: sms-checker-config
            - secretRef:
                name: sms-checker-secret
          ports:
            - containerPort: {{ .Values.app.port }}
