{{- range $key, $val := .Values.app.versions }}
{{- if $val.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-checker-app-{{ $val.versionLabel }}
  labels:
    app: sms-checker-app
    version: {{ $val.versionLabel }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sms-checker-app
      version: {{ $val.versionLabel }}
  template:
    metadata:
      labels:
        app: sms-checker-app
        version: {{ $val.versionLabel }}
    spec:
      containers:
        - name: sms-checker-app
          image: "{{ $val.image }}"
          imagePullPolicy: {{ $val.pullPolicy }}
          ports:
            - containerPort: {{ $val.port }}
          env:
            - name: MODEL_HOST
              valueFrom:
                configMapKeyRef:
                  name: sms-checker-config
                  key: MODEL_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: sms-checker-config
                  key: APP_PORT
---
{{- end }}
{{- end }}
