apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-checker-config
data:
  MODEL_SERVICE_PORT: "{{ .Values.modelService.port }}"
  
  APP_PORT: "{{ .Values.app.port }}"
  MODEL_HOST: "{{ .Values.app.modelHost }}"
