apiVersion: v1
kind: ConfigMap
metadata:
  name: sms-checker-dashboards
  labels:
    grafana_dashboard: "1" 
    release: myprom
data: 
  sms-ops-dashboard.json: |-
{{ .Files.Get "dashboard/grafana1.json" | indent 4 }}

  sms-experiment-dashboard.json: |-
{{ .Files.Get "dashboard/grafana2.json" | indent 4 }}
