{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sms-checker-ingress
  labels:
    app: sms-checker
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx    
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          # Frontend UI
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sms-checker-app
                port:
                  number: {{ .Values.app.versions.v1.port }}

          - path: /metrics/sms-checker-app(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sms-checker-app
                port:
                  number: {{ .Values.app.versions.v1.port }}

          - path: /metrics/model-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: model-service
                port:
                  number: {{ .Values.modelService.versions.v1.port }}
{{- end }}
