{{- range $key, $val := .Values.modelService.versions }}
{{- if $val.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-{{ $val.versionLabel }}
  labels:
    app: model-service
    version: {{ $val.versionLabel }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      version: {{ $val.versionLabel }}
  template:
    metadata:
      labels:
        app: model-service
        version: {{ $val.versionLabel }}
    spec:
      containers:
        - name: model-service
          image: "{{ $val.image }}"
          imagePullPolicy: {{ $val.pullPolicy }}
          ports:
            - containerPort: {{ $val.port }}
          env:
            - name: MODEL_PORT
              valueFrom:
                configMapKeyRef:
                  name: sms-checker-config
                  key: MODEL_SERVICE_PORT
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sms-checker-secret
                  key: API_KEY
          
          volumeMounts:
            - name: shared-storage
              mountPath: {{ $val.storage.mountPath }}
      
      volumes:
        - name: shared-storage
          hostPath:
            path: {{ $val.storage.path }}
            type: DirectoryOrCreate
---
{{- end }}
{{- end }}
