{{- range $versionName, $version := .Values.modelService.versions }}
{{- if $version.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-service-{{ $versionName }}
  labels:
    app: model-service
    version: {{ $versionName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      version: {{ $versionName }}
  template:
    metadata:
      labels:
        app: model-service
        version: {{ $versionName }}
    spec:
      containers:
        - name: model-service
          image: {{ $version.image }}
          imagePullPolicy: {{ $version.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: {{ $version.port }}
          volumeMounts:
            - name: model-storage
              mountPath: {{ $version.storage.mountPath }}
      volumes:
        - name: model-storage
          persistentVolumeClaim:
            claimName:  model-service-{{ $versionName }}-pvc
---
{{- end }}
{{- end }}
